[package]
name = "lab_rust_event_sourcing"
version = "0.1.0"
authors = ["Marcus Rådell <marcus@radell.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = {version = "0.8", features = ["v4"]}